### ISSUE TITLE
idea for loading image-links

### ISSUE THREAD

**Issue by nsklaus** [0xc22b/textfirst#1]
hi, i'm exactly in the situation described, slow connection with quotas.
so textfirst is great for me, thanks for doing it !

as an idea for the problem about "image-links that cannot be clicked to reveal the image but instead do follow the link":  why not use a key as a modifier ?

for example, on mouse click on a image-link
if that key is pressed: don't follow the link but just load the image instead.
if that key is not pressed: then follow the link as normal

**Comment by 0xc22b** [comment]
Hi,
That's a brilliant idea.
I'll find time to implement it and let you know.
Thanks!

**Comment by nsklaus** [comment]
hey, thanks :)
can't wait to see..
